source "https://rubygems.org"

gem "jekyll", "~> 4.3"  # Use latest Jekyll version
gem "just-the-docs"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

# Add any other plugins you need
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  # etc.
end
